### ISSUE TITLE
OPT20030: Pecha.org categorizer

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/pecha_org_tools#1]
## Description
A python package to get category for a particular pecha. 

## Features:
- A user-friendly spreadsheet interface that allows easy editing and updates.
- Simple, one-line integration for seamless usage of the package.

## Important Note
A package already exist [here](https://github.com/OpenPecha/pecha.org-data/blob/main/parse_catalog.py). But might need improvment.

## Expected Output
Input a title or a category name and it return the neccessary category format needed for pecha.org format.
For example:
 Input: =>ཀུན་བཟང་སྨོན་ལམ།
 Output:=>
```
{
             {
                "name": "ཁ་འདོན།",
                "heDesc": "",
                "heShortDesc": "ཆོ་ག་དང་འདོན་ཆ།"
            },
            {
                "name": "སྨོན་ལམ།",
                "heDesc": "",
                "heShortDesc": ""
            },
            {
                "name": "ཀུན་བཟང་སྨོན་ལམ།",
                "heDesc": "",
                "heShortDesc": "སྨོན་ལམ་སྟོབས་པོ་ཆེ།"
            }
 }
```

## Implementation Steps

- [x] Understand the category structure design of pecha.org.
- [x] Create a category format in the spreadsheet.
- [x] Write code to retrieve categories from the spreadsheet.

**Comment by tenzin3** [comment]
Last categorgy should contain the book title. 
Second Last category is usually the root text/commentary text.


Important Note:
Titles, desc, short desc, english version should be in the same spreedsheet.
desc and shortdesc might be long in some cases.

**Comment by tenzin3** [comment]
![Image](https://github.com/user-attachments/assets/2ff06153-8db9-45d1-8876-68e823f3ee46)

Fig: Spreedsheet containing both tibetan and english category details.
Example==:>`སྨོན་ལམ།(སྨོན་ལམ་འགྲེལ་བཤད་)(སྨོན་ལམ་འགྲེལ་བཤད་ཐུང་ཐུང་)`
`སྨོན་ལམ།`=>Title
`སྨོན་ལམ་འགྲེལ་བཤད་`=> Description
`སྨོན་ལམ་འགྲེལ་བཤད་ཐུང་ཐུང་`=> Short Description

First text is always title, text in first paranthesis is Description, text in second paranthesis is Short Description.

The cell following this or right cell `Aspiration Prayer (Explanation of Aspiration Prayer)(Brief Explanation of Aspiration Prayer)` is the english version of this particular category.
